//! Category groupings and enumeration methods for [`DrawingToolType`].
//!
//! Provides methods to query tools by category name, list all available
//! categories, enumerate all 97 tools, and look up SVG icon paths.

use super::DrawingToolType;

impl DrawingToolType {
    /// Returns all tools belonging to the given category (case-insensitive).
    ///
    /// Valid category names: `"cursors"`, `"lines"`, `"channels"`, `"pitchforks"`,
    /// `"fibonacci"`, `"gann"`, `"patterns"`, `"elliott"`, `"cycles"`,
    /// `"projection"`, `"volume"`, `"measurers"`, `"brushes"`, `"arrows"`,
    /// `"shapes"`, `"annotations"`, `"content"`, `"icons"`.
    ///
    /// Returns `[TrendLine]` for unrecognized categories as a safe fallback.
    pub fn by_category(category: &str) -> Vec<Self> {
        match category.to_lowercase().as_str() {
            "cursors" => vec![
                Self::CrossCursor,
                Self::DotCursor,
                Self::ArrowCursor,
                Self::Eraser,
            ],
            "lines" => vec![
                Self::TrendLine,
                Self::Ray,
                Self::InfoLine,
                Self::ExtendedLine,
                Self::HorizontalLine,
                Self::HorizontalRay,
                Self::VerticalLine,
                Self::CrossLine,
                Self::TrendAngle,
            ],
            "channels" => vec![
                Self::ParallelChannel,
                Self::RegressionTrend,
                Self::FlatTopBottom,
                Self::DisjointChannel,
            ],
            "pitchforks" => vec![
                Self::Pitchfork,
                Self::SchiffPitchfork,
                Self::ModifiedSchiffPitchfork,
                Self::InsidePitchfork,
            ],
            "fibonacci" => vec![
                Self::FibonacciRetracement,
                Self::FibonacciExtension,
                Self::FibonacciChannel,
                Self::FibonacciTimeZones,
                Self::FibonacciSpeedFan,
                Self::TrendBasedFibTime,
                Self::FibonacciCircles,
                Self::FibonacciSpiral,
                Self::FibonacciSpeedResistanceArcs,
                Self::FibonacciWedge,
                Self::Pitchfan,
            ],
            "gann" => vec![
                Self::GannBox,
                Self::GannSquare,
                Self::GannFixed,
                Self::GannFan,
            ],
            "patterns" => vec![
                Self::XABCDPattern,
                Self::CypherPattern,
                Self::HeadAndShoulders,
                Self::ABCDPattern,
                Self::TrianglePattern,
                Self::ThreeDrivesPattern,
            ],
            "elliott" => vec![
                Self::ElliottImpulse,
                Self::ElliottCorrection,
                Self::ElliottTriangle,
                Self::ElliottDoubleCombo,
                Self::ElliottTripleCombo,
            ],
            "cycles" => vec![Self::CyclicLines, Self::TimeCycles, Self::SineLine],
            "projection" => vec![
                Self::LongPos,
                Self::ShortPos,
                Self::Forecast,
                Self::BarsPattern,
                Self::GhostFeed,
                Self::ProjectionTool,
            ],
            "volume" => vec![
                Self::AnchoredVWAP,
                Self::FixedRangeVolumeProfile,
                Self::AnchoredVolumeProfile,
            ],
            "measurers" => vec![
                Self::Measure,
                Self::PriceRange,
                Self::DateRange,
                Self::DateAndPriceRange,
            ],
            "brushes" => vec![Self::Brush, Self::Highlighter, Self::Paintbrush],
            "arrows" => vec![
                Self::ArrowMarker,
                Self::Arrow,
                Self::ArrowMarkUp,
                Self::ArrowMarkDown,
            ],
            "shapes" => vec![
                Self::Rect,
                Self::RotatedRect,
                Self::Path,
                Self::Circle,
                Self::Ellipse,
                Self::Polyline,
                Self::Triangle,
                Self::Arc,
                Self::Curve,
                Self::DoubleCurve,
            ],
            "annotations" => vec![
                Self::TextLabel,
                Self::AnchoredText,
                Self::Note,
                Self::PriceNote,
                Self::AnchoredNote,
                Self::Table,
                Self::Callout,
                Self::Comment,
                Self::PriceLabel,
                Self::Signpost,
                Self::FlagNote,
            ],
            "content" => vec![Self::Image, Self::Tweet, Self::Idea],
            "icons" => vec![Self::FontIcon],
            _ => vec![Self::TrendLine],
        }
    }

    /// Returns the names of all 18 tool categories in display order.
    pub fn categories() -> &'static [&'static str] {
        &[
            "Cursors",
            "Lines",
            "Channels",
            "Pitchforks",
            "Fibonacci",
            "Gann",
            "Patterns",
            "Elliott",
            "Cycles",
            "Projection",
            "Volume",
            "Measurers",
            "Brushes",
            "Arrows",
            "Shapes",
            "Annotations",
            "Content",
            "Icons",
        ]
    }

    /// Returns a static slice of all 97 tool types in canonical order.
    ///
    /// The order matches the category groupings: cursors, lines, channels,
    /// pitchforks, fibonacci, gann, patterns, elliott, cycles, projection,
    /// volume, measurers, brushes, arrows, shapes, annotations, content, icons.
    pub fn all() -> &'static [Self] {
        &[
            // Cursors (4)
            Self::CrossCursor,
            Self::DotCursor,
            Self::ArrowCursor,
            Self::Eraser,
            // Lines (9)
            Self::TrendLine,
            Self::Ray,
            Self::InfoLine,
            Self::ExtendedLine,
            Self::HorizontalLine,
            Self::HorizontalRay,
            Self::VerticalLine,
            Self::CrossLine,
            Self::TrendAngle,
            // Channels (4)
            Self::ParallelChannel,
            Self::RegressionTrend,
            Self::FlatTopBottom,
            Self::DisjointChannel,
            // Pitchforks (4)
            Self::Pitchfork,
            Self::SchiffPitchfork,
            Self::ModifiedSchiffPitchfork,
            Self::InsidePitchfork,
            // Fibonacci (11)
            Self::FibonacciRetracement,
            Self::FibonacciExtension,
            Self::FibonacciChannel,
            Self::FibonacciTimeZones,
            Self::FibonacciSpeedFan,
            Self::TrendBasedFibTime,
            Self::FibonacciCircles,
            Self::FibonacciSpiral,
            Self::FibonacciSpeedResistanceArcs,
            Self::FibonacciWedge,
            Self::Pitchfan,
            // Gann (4)
            Self::GannBox,
            Self::GannSquare,
            Self::GannFixed,
            Self::GannFan,
            // Patterns (6)
            Self::XABCDPattern,
            Self::CypherPattern,
            Self::HeadAndShoulders,
            Self::ABCDPattern,
            Self::TrianglePattern,
            Self::ThreeDrivesPattern,
            // Elliott Wave (5)
            Self::ElliottImpulse,
            Self::ElliottCorrection,
            Self::ElliottTriangle,
            Self::ElliottDoubleCombo,
            Self::ElliottTripleCombo,
            // Cycles (3)
            Self::CyclicLines,
            Self::TimeCycles,
            Self::SineLine,
            // Projection (6)
            Self::LongPos,
            Self::ShortPos,
            Self::Forecast,
            Self::BarsPattern,
            Self::GhostFeed,
            Self::ProjectionTool,
            // Volume (3)
            Self::AnchoredVWAP,
            Self::FixedRangeVolumeProfile,
            Self::AnchoredVolumeProfile,
            // Measurers (4)
            Self::Measure,
            Self::PriceRange,
            Self::DateRange,
            Self::DateAndPriceRange,
            // Brushes (3)
            Self::Brush,
            Self::Highlighter,
            Self::Paintbrush,
            // Arrows (4)
            Self::ArrowMarker,
            Self::Arrow,
            Self::ArrowMarkUp,
            Self::ArrowMarkDown,
            // Shapes (10)
            Self::Rect,
            Self::RotatedRect,
            Self::Path,
            Self::Circle,
            Self::Ellipse,
            Self::Polyline,
            Self::Triangle,
            Self::Arc,
            Self::Curve,
            Self::DoubleCurve,
            // Annotations (11)
            Self::TextLabel,
            Self::AnchoredText,
            Self::Note,
            Self::PriceNote,
            Self::AnchoredNote,
            Self::Table,
            Self::Callout,
            Self::Comment,
            Self::PriceLabel,
            Self::Signpost,
            Self::FlagNote,
            // Content (3)
            Self::Image,
            Self::Tweet,
            Self::Idea,
            // Icons (1)
            Self::FontIcon,
        ]
    }

    /// Returns the relative path to the SVG icon file for this tool.
    ///
    /// Paths are relative to the application's asset root (e.g.,
    /// `"assets/icons/drawing/trend-line.svg"`). Used by the toolbar UI to
    /// display tool icons.
    pub fn icon(&self) -> &str {
        match self {
            Self::CrossCursor => "assets/icons/drawing/cursor-cross.svg",
            Self::DotCursor => "assets/icons/drawing/cursor-dot.svg",
            Self::ArrowCursor => "assets/icons/drawing/cursor-arrow.svg",
            Self::Eraser => "assets/icons/drawing/eraser.svg",
            Self::TrendLine => "assets/icons/drawing/trend-line.svg",
            Self::Ray => "assets/icons/drawing/ray.svg",
            Self::InfoLine => "assets/icons/drawing/info-line.svg",
            Self::ExtendedLine => "assets/icons/drawing/extended.svg",
            Self::HorizontalLine => "assets/icons/drawing/horz-line.svg",
            Self::HorizontalRay => "assets/icons/drawing/horz-ray.svg",
            Self::VerticalLine => "assets/icons/drawing/vertical-line.svg",
            Self::CrossLine => "assets/icons/drawing/cross-line.svg",
            Self::TrendAngle => "assets/icons/drawing/trend-angle.svg",
            Self::ParallelChannel => "assets/icons/drawing/parallel-channel.svg",
            Self::RegressionTrend => "assets/icons/drawing/regression-trend.svg",
            Self::FlatTopBottom => "assets/icons/drawing/flat-bottom.svg",
            Self::DisjointChannel => "assets/icons/drawing/disjoint-angle.svg",
            Self::Pitchfork => "assets/icons/drawing/pitchfork.svg",
            Self::SchiffPitchfork => "assets/icons/drawing/schiff-pitchfork.svg",
            Self::ModifiedSchiffPitchfork => "assets/icons/drawing/schiff-pitchfork2.svg",
            Self::InsidePitchfork => "assets/icons/drawing/inside-pitchfork.svg",
            Self::FibonacciRetracement => "assets/icons/drawing/fib-retracement.svg",
            Self::FibonacciExtension => "assets/icons/drawing/fib-extension.svg",
            Self::FibonacciChannel => "assets/icons/drawing/fib-channel.svg",
            Self::FibonacciTimeZones => "assets/icons/drawing/fib-time-zone.svg",
            Self::FibonacciSpeedFan => "assets/icons/drawing/fib-speed-resistance-fan.svg",
            Self::TrendBasedFibTime => "assets/icons/drawing/trend-based-fib-time.svg",
            Self::FibonacciCircles => "assets/icons/drawing/fib-circles.svg",
            Self::FibonacciSpiral => "assets/icons/drawing/fib-spiral.svg",
            Self::FibonacciSpeedResistanceArcs => {
                "assets/icons/drawing/fib-speed-resistance-arcs.svg"
            }
            Self::FibonacciWedge => "assets/icons/drawing/fib-wedge.svg",
            Self::Pitchfan => "assets/icons/drawing/pitchfan.svg",
            Self::GannBox => "assets/icons/drawing/gann-box.svg",
            Self::GannSquare => "assets/icons/drawing/gann-square.svg",
            Self::GannFixed => "assets/icons/drawing/gann-fixed.svg",
            Self::GannFan => "assets/icons/drawing/gann-fan.svg",
            Self::XABCDPattern => "assets/icons/drawing/xabcd-pattern.svg",
            Self::CypherPattern => "assets/icons/drawing/cypher-pattern.svg",
            Self::HeadAndShoulders => "assets/icons/drawing/head-and-shoulders.svg",
            Self::ABCDPattern => "assets/icons/drawing/abcd.svg",
            Self::TrianglePattern => "assets/icons/drawing/triangle-pattern.svg",
            Self::ThreeDrivesPattern => "assets/icons/drawing/three-drivers.svg",
            Self::ElliottImpulse => "assets/icons/drawing/elliott-impulse.svg",
            Self::ElliottCorrection => "assets/icons/drawing/elliott-correction.svg",
            Self::ElliottTriangle => "assets/icons/drawing/elliott-triangle.svg",
            Self::ElliottDoubleCombo => "assets/icons/drawing/elliott-double-combo.svg",
            Self::ElliottTripleCombo => "assets/icons/drawing/elliott-triple-combo.svg",
            Self::CyclicLines => "assets/icons/drawing/circle-lines.svg",
            Self::TimeCycles => "assets/icons/drawing/time-cycles.svg",
            Self::SineLine => "assets/icons/drawing/sine-line.svg",
            Self::LongPos => "assets/icons/drawing/long-position.svg",
            Self::ShortPos => "assets/icons/drawing/short-position.svg",
            Self::Forecast => "assets/icons/drawing/projection.svg",
            Self::BarsPattern => "assets/icons/drawing/bars-pattern.svg",
            Self::GhostFeed => "assets/icons/drawing/ghost-feed.svg",
            Self::ProjectionTool => "assets/icons/drawing/projection.svg",
            Self::AnchoredVWAP => "assets/icons/drawing/anchored-vwap.svg",
            Self::FixedRangeVolumeProfile => "assets/icons/drawing/fixed-range-volume-profile.svg",
            Self::AnchoredVolumeProfile => "assets/icons/drawing/anchored-volume-profile.svg",
            Self::Measure => "assets/icons/drawing/measure.svg",
            Self::PriceRange => "assets/icons/drawing/price-range.svg",
            Self::DateRange => "assets/icons/drawing/date-range.svg",
            Self::DateAndPriceRange => "assets/icons/drawing/date-and-price-range.svg",
            Self::Brush => "assets/icons/drawing/brush.svg",
            Self::Highlighter => "assets/icons/drawing/highlighter.svg",
            Self::Paintbrush => "assets/icons/drawing/paintbrush.svg",
            Self::ArrowMarker => "assets/icons/drawing/arrow-marker.svg",
            Self::Arrow => "assets/icons/drawing/arrow.svg",
            Self::ArrowMarkUp => "assets/icons/drawing/arrow-mark-up.svg",
            Self::ArrowMarkDown => "assets/icons/drawing/arrow-mark-down.svg",
            Self::Rect => "assets/icons/drawing/rect.svg",
            Self::RotatedRect => "assets/icons/drawing/rotated-rect.svg",
            Self::Path => "assets/icons/drawing/path.svg",
            Self::Circle => "assets/icons/drawing/circle.svg",
            Self::Ellipse => "assets/icons/drawing/ellipse.svg",
            Self::Polyline => "assets/icons/drawing/polyline.svg",
            Self::Triangle => "assets/icons/drawing/triangle.svg",
            Self::Arc => "assets/icons/drawing/arc.svg",
            Self::Curve => "assets/icons/drawing/bezier-quadro.svg",
            Self::DoubleCurve => "assets/icons/drawing/bezier-cubic.svg",
            Self::TextLabel => "assets/icons/drawing/text.svg",
            Self::AnchoredText => "assets/icons/drawing/anchored-text.svg",
            Self::Note => "assets/icons/drawing/note.svg",
            Self::PriceNote => "assets/icons/drawing/price-note.svg",
            Self::AnchoredNote => "assets/icons/drawing/anchored-note.svg",
            Self::Table => "assets/icons/drawing/table.svg",
            Self::Callout => "assets/icons/drawing/callout.svg",
            Self::Comment => "assets/icons/drawing/comment.svg",
            Self::PriceLabel => "assets/icons/drawing/price-label.svg",
            Self::Signpost => "assets/icons/drawing/signpost.svg",
            Self::FlagNote => "assets/icons/drawing/flag-mark.svg",
            Self::Image => "assets/icons/drawing/image.svg",
            Self::Tweet => "assets/icons/drawing/tweet.svg",
            Self::Idea => "assets/icons/drawing/idea.svg",
            Self::FontIcon => "assets/icons/drawing/emoji.svg",
        }
    }
}
